trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/v*

pr:
  - master

variables:
  PYTHONUNBUFFERED: 1
  ATEST_RETRIES: 1
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

  PY_JLSP_VERSION: 0.8.0
  JS_JLLSP_VERSION: 1.0.0
  JS_JLG2D_VERSION: 1.0.0

  FIRST_PARTY_LABEXTENSIONS: >-
    packages/jupyterlab-lsp/krassowski-jupyterlab-lsp-$(JS_JLLSP_VERSION).tgz

  LINKED_EXTENSIONS: >-
    packages/lsp-ws-connection
    packages/jupyterlab-go-to-definition

jobs:
  - template: ci/job.lint.yml
  - template: ci/job.test.yml
  - template: ci/job.docs.yml
