trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/v*

pr:
  - master

variables:
  PYTHONUNBUFFERED: 1
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  PY_JLSP_VERSION: 0.6.0b0
  JS_JLLSP_VERSION: 0.5.0

jobs:
  - template: ci/job.test.yml
  - template: ci/job.combine.yml
